import "./globals.css";
import { roboto } from "@/app/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${roboto.variable}`}>
      <body className="min-h-screen"></body>
    </html>
  );
}
